tunnel: 12596af8-7f3d-4ed5-953f-b722d105f114
credentials-file: /opt/libermedia/.cloudflared/12596af8-7f3d-4ed5-953f-b722d105f114.json

ingress:
  - hostname: nostr.libernet.app
    service: http://127.0.0.1:8081
  - service: http_status:404
